### ISSUE TITLE
Error running container. Container stops

### ISSUE THREAD

**Issue by dalareo** [moritzfl/docker-fiduswriter#3]
I get this log:

```
*** Running as user fiduswriter ...
*** Moving fiduswriter.sql to /data ...
mv: cannot create regular file '/data/fiduswriter.sql': Permission denied
*** Moving media-folder to /data ...
mv: cannot create directory '/data/media': Permission denied
ln: /fiduswriter/media: cannot overwrite directory
*** Moving configuration.py to /data ...
mv: cannot create regular file '/data/configuration.py': Permission denied
*** Starting server ...
Traceback (most recent call last):
  File "manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/home/fiduswriter/.local/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/home/fiduswriter/.local/lib/python2.7/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/fiduswriter/.local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/fiduswriter/.local/lib/python2.7/site-packages/django/core/management/base.py", line 329, in execute
    self.check_migrations()
  File "/home/fiduswriter/.local/lib/python2.7/site-packages/django/core/management/base.py", line 422, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/home/fiduswriter/.local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/fiduswriter/.local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 52, in __init__
    self.build_graph()
  File "/home/fiduswriter/.local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 209, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/home/fiduswriter/.local/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 65, in applied_migrations
    self.ensure_schema()
  File "/home/fiduswriter/.local/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 52, in ensure_schema
    if self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor()):
  File "/home/fiduswriter/.local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 254, in cursor
    return self._cursor()
  File "/home/fiduswriter/.local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 229, in _cursor
    self.ensure_connection()
  File "/home/fiduswriter/.local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/home/fiduswriter/.local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/fiduswriter/.local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/home/fiduswriter/.local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 189, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/fiduswriter/.local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 198, in get_new_connection
    conn = Database.connect(**conn_params)
django.db.utils.OperationalError: unable to open database file
```

**Comment by moritzfl** [comment]
this is most likely due to insufficient permissions on the host machine for the user fiduswriter (should only occur on linux hosts)
As mentioned in README.md you need to enable file access to the according directory on the host machine first. 

Not perfect by any means so if you can think of a way to solve this in another way, let me know ;)

**Comment by moritzfl** [comment]
closing this for now - if you still have issues let me know
