### ISSUE TITLE
problems after using docker

### ISSUE THREAD

**Issue by palices** [moritzfl/docker-fiduswriter#6]
the command with the directory changed
` $ docker run -d -v /host/directory:/data -p 8000:8000 --name moritzf-fiduswriter moritzf/fiduswriter:latest`
used after installation reports always the same problem "$. command not found"

Also after the installation wit the **sudo docker run -it moritzf/fiduswriter** reports the following errors
[9598f3bd898: Pull complete 
Digest: sha256:c5844b8d0f29e986e921a4bc8f3bf8ab65fdea3f86d00580a1f6987cf3430306
Status: Downloaded newer image for moritzf/fiduswriter:latest
*** Running as user fiduswriter ...
*** Moving fiduswriter.sql to /data ...
mv: cannot create regular file '/data/fiduswriter.sql': Permission denied
*** Moving media-folder to /data ...
mv: cannot create directory '/data/media': Permission denied
ln: /fiduswriter/media: cannot overwrite directory
*** Moving configuration.py to /data ...
mv: cannot create regular file '/data/configuration.py': Permission denied
*** Starting server ...
Traceback (most recent call last):
  File "/home/fiduswriter/.local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/home/fiduswriter/.local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 189, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/fiduswriter/.local/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 198, in get_new_connection
    conn = Database.connect(**conn_params)
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/home/fiduswriter/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/fiduswriter/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/fiduswriter/.local/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/fiduswriter/.local/lib/python3.6/site-packages/django/core/management/base.py", line 329, in execute
    self.check_migrations()
  File "/home/fiduswriter/.local/lib/python3.6/site-packages/django/core/management/base.py", line 422, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/home/fiduswriter/.local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/fiduswriter/.local/lib/python3.6/site-packages/django/db/migrations/loader.py", line 52, in __init__
    self.build_graph()
  File "/home/fiduswriter/.local/lib/python3.6/site-packages/django/db/migrations/loader.py", line 209, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/home/fiduswriter/.local/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 65, in applied_migrations
    self.ensure_schema()
  File "/home/fiduswriter/.local/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 52, in ensure_schema
    if self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor()):
  File "/home/fiduswriter/.local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 254, in cursor
    return self._cursor()
  File "/home/fiduswriter/.local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 229, in _cursor
    self.ensure_connection()
  File "/home/fiduswriter/.local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/home/fiduswriter/.local/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/fiduswriter/.local/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/fiduswriter/.local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/home/fiduswriter/.local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 189, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/fiduswriter/.local/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 198, in get_new_connection
    conn = Database.connect(**conn_params)
django.db.utils.OperationalError: unable to open database file
](url)

What i'm doing wrong?

Thanks

**Comment by moritzfl** [comment]
First of all I want to say sorry for the late answer. I was in the final (and very stressful) phase of my master thesis when this issue was opened and somehow failed to answer it afterwards.

I am assuming that you are using a Linux host. On Linux, you need to adjust the file permissions for the folder that you map to the docker containers /data folder. I think the problem lies there because the log indicates that fiduswriter does not have access to the according files. In the readme file this is described through the command:

$ sudo chown -R 999:999 /host/directory

**Comment by bytersproblem** [comment]
I am having the same issue and `sudo chown -R 999:999 /host/directory` does not solve the problem. It still says permission denied. Thanks!
